Resources:
  LambdaRole3A44B857:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CollectorStack/LambdaRole/Resource
  LambdaRoleDefaultPolicy75625A82:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:PutObject
            Effect: Allow
            Resource: arn:aws:s3:::shuraosipov-rss-feed-analysis/*
          - Action: sns:Publish
            Effect: Allow
            Resource: arn:aws:sns:us-east-1:419091122511:shuraosipov-default-topic
        Version: "2012-10-17"
      PolicyName: LambdaRoleDefaultPolicy75625A82
      Roles:
        - Ref: LambdaRole3A44B857
    Metadata:
      aws:cdk:path: CollectorStack/LambdaRole/DefaultPolicy/Resource
  CollectorFunction30759564:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 5419658578e060f32ff277d456bec3de0c0a442df835dad2e11ed527edcce177.zip
      Role:
        Fn::GetAtt:
          - LambdaRole3A44B857
          - Arn
      Environment:
        Variables:
          BUCKET_NAME: shuraosipov-rss-feed-analysis
          DAYS_RANGE: "1"
          FEED_URL: https://aws.amazon.com/about-aws/whats-new/recent/feed/
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:419091122511:shuraosipov-default-topic
      Handler: lambda_function.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:419091122511:layer:feedparser:2
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1
      Runtime: python3.9
      Timeout: 15
    DependsOn:
      - LambdaRoleDefaultPolicy75625A82
      - LambdaRole3A44B857
    Metadata:
      aws:cdk:path: CollectorStack/CollectorFunction/Resource
      aws:asset:path: /home/shuraosipov/workspace/aws_rss_feed_analysis/collector/lambda
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CollectorRuleE13FEC75:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(02 00 * * ? *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - CollectorFunction30759564
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: CollectorStack/CollectorRule/Resource
  CollectorRuleAllowEventRuleCollectorStackCollectorFunctionDF8B6A7AB49C3EC7:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CollectorFunction30759564
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - CollectorRuleE13FEC75
          - Arn
    Metadata:
      aws:cdk:path: CollectorStack/CollectorRule/AllowEventRuleCollectorStackCollectorFunctionDF8B6A7A
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02O3QqDMAxGn8X7mv0og11OYdfiHkBqzVymtmDaDSm++6pusKvzfTmE5AhpCvtIvjlWTRf3VIO/Wak6EUaVJzmAL02PIr/rlYXpSU1L3dIsejnUjQR/dVpZMnpx/7nAcSDm0GbBSSWZ0TJcFoQOmVMd2kwyCnyhDsqX7nswcJ5FiWzcqFCsO+G7lnS7+p8IOTe6IbseKSb7MHqXwBkOp+jJRPHotKUBodz4AS5unz/2AAAA
    Metadata:
      aws:cdk:path: CollectorStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

